---
name: Verify Pull Request

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.go'
      - .go-version
      - .pre-commit-config.yaml
      - go.mod
      - go.sum

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'go-template'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup go'
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache-file: go.sum

      - name: 'Run tests'
        run: go test -v ./...

  pre-commit:
    name: 'Run pre-commit check'
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'go-template'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup go'
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache-file: go.sum

      - name: 'Run pre-commit check'
        uses: pre-commit/action@v3.0.0
